name = "durable-down-detector-workers-js"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "e30ff9682b2d2e661fd5713ead4e296e"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-23"
kv_namespaces = [
    { binding = "URLS", id = "286e9d5a9f5446338766bfa010c857b9" }
]

[build]
command = "npm install && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "UPTIME", class_name = "UptimeActor"}]

[[migrations]]
tag = "v3" # Should be unique for each entry
new_classes = ["UptimeActor"]
